Name: Training
Type: ProjectFolder
Children:
- Name: Localization
  Type: PropertyGroup
  Children:
  - Name: Locales
    Id: g=7909ce578c56922328a4187b09cf86a1
    Type: BaseDataVariableType
    DataType: LocaleId
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: ["en-US","it-IT"]
  - Name: LocaleFallbackList
    Type: BaseDataVariableType
    DataType: LocaleId
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: ["en-US"]
- Name: Authentication
  Type: PropertyGroup
  Children:
  - Name: DefaultUserFolder
    Type: NodePointer
    DataType: NodeId
    Value: "/Objects/Training/Security/Users"
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: "/Types/ObjectTypes/BaseObjectType/FolderType"
- Name: PasswordPolicy
  Type: PasswordPolicy
  Children:
  - Name: MaximumPasswordAge
    Type: BaseDataVariableType
    DataType: UInt16
  - Name: EnforcePasswordHistory
    Type: BaseDataVariableType
    DataType: Byte
    Value: 1
  - Name: MinimumPasswordAge
    Type: BaseDataVariableType
    DataType: UInt16
  - Name: MinimumPasswordLength
    Type: BaseDataVariableType
    DataType: Byte
    Value: 8
- Name: AlarmConfiguration
  Type: PropertyGroup
- File: UI/UI.yaml
- File: Model/Model.yaml
- File: Converters/Converters.yaml
- File: Alarms/Alarms.yaml
- File: Recipes/Recipes.yaml
- File: Loggers/Loggers.yaml
- File: DataStores/DataStores.yaml
- File: Reports/Reports.yaml
- File: 'OPC-UA/OPC-UA.yaml'
- File: CommDrivers/CommDrivers.yaml
- File: NetLogic/NetLogic.yaml
- File: Security/Security.yaml
- File: System/System.yaml
- File: Translations/Translations.yaml
- File: Retentivity/Retentivity.yaml
- File: AlarmTypes/AlarmTypes.yaml
- Name: RecipeSchema1
  Type: Alias
  DataType: NodeId
  Value: "/Objects/Training/Recipes/RecipeSchema1/EditModel"
  Children:
  - Name: Kind
    Type: PropertyType
    DataType: NodeId
    Value: "/Objects/Training/Recipes/RecipeSchema1/EditModel"
