Name: Recipe
Id: g=ec4fb89e4193ffc753281bae55342b55
Type: FolderType
Children:
- Name: Variable1
  Id: g=155ee563eae148a35c95474e98a3e1cc
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
- Name: Variable2
  Id: g=7b754225d77572ef29dfcd863db0bc02
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
- Name: Variable3
  Id: g=fada9262d915a18a2f091dcf39daedae
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
- Name: Variable4
  Id: g=1a5859e4de626e8efff76cd24a87e04d
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
